name: npm-publish
on:
  push:
    branches:
      - master # Change this to your default branch
      - bugfix
jobs:
  npm-publish:
    name: npm-publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: '12.x'

      - name: Use cached node_modules
        uses: actions/cache@master
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          CI: true

      # Publish to Node Package Manager
      # - name: Set registry to NPM
      #   uses: actions/setup-node@master
      #   with:
      #     registry-url: 'https://registry.npmjs.org'
      # - name: Update Publish Config
      #   run: sed -i 's^registry-url^registry.npmjs.org^' package.json
      # - name: Publish to NPM
      #   run: npm publish --access public
      #   env:
      #     CI: true
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      # Publish to GitHub Package Registry
      - name: Set registry to GPR
        uses: actions/setup-node@master
        with:
          registry-url: https://npm.pkg.github.com/
          scope: 'alehechka'
      - name: Update Publish Config
        run: |
          sed -i 's^registry-url^npm.pkg.github.com/@${{ github.actor }}^' package.json
          echo package.json
      - name: Publish to GitHub Package Registry
        run: npm publish --access public
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
